workflows:
  heliboard-mo-debug:
    name: Heliboard-Mo Debug
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Make gradlew executable
        script: chmod +x gradlew
      - name: Build debug APK
        script: ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk

  heliboard-mo-release:
    name: Heliboard-Mo Release
    instance_type: linux_x2
    max_build_duration: 90
    environment:
      java: 17
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    scripts:
      - name: Make gradlew executable
        script: chmod +x gradlew
      - name: Build release APK
        script: ./gradlew :app:assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
